ServiceAssetTracker/Models/ResellerViewModels/Reseller_Service.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ServiceAssetTracker.Models.ResellerViewModels
{
    public class Reseller_Service
    {
        [Key]
        public int ResellerServiceId { get; set; }
        public int ResellerId { get; set; }
        public Reseller Reseller { get; set; }
        public string ShortDescription { get; set; }
        [ForeignKey("Categories")]
        public int CategoryId { get; set; }
        public Categories Categories { get; set; }
        public string Task { get; set; }
        public double Price { get; set; }
        public string Metric { get; set; }
    }
}

ServiceAssetTracker/Controllers/Reseller_ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceAssetTracker.Data;
using ServiceAssetTracker.Models.ResellerViewModels;

namespace ServiceAssetTracker.Controllers
{
    public class Reseller_ServiceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Reseller_ServiceController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reseller_Service
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Reseller_Service.Include(r => r.Categories).Include(r => r.Reseller);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reseller_Service/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reseller_Service = await _context.Reseller_Service
                .Include(r => r.Categories)
                .Include(r => r.Reseller)
                .SingleOrDefaultAsync(m => m.ResellerServiceId == id);
            if (reseller_Service == null)
            {
                return NotFound();
            }

            return View(reseller_Service);
        }

        // GET: Reseller_Service/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["ResellerId"] = new SelectList(_context.Reseller, "ResellerId", "TradingName");
            return View();
        }

        // POST: Reseller_Service/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResellerServiceId,ResellerId,ShortDescription,CategoryId,Task,Price,Metric")] Reseller_Service reseller_Service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reseller_Service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", reseller_Service.CategoryId);
            ViewData["ResellerId"] = new SelectList(_context.Reseller, "ResellerId", "TradingName", reseller_Service.ResellerId);
            return View(reseller_Service);
        }

        // GET: Reseller_Service/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reseller_Service = await _context.Reseller_Service.SingleOrDefaultAsync(m => m.ResellerServiceId == id);
            if (reseller_Service == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", reseller_Service.CategoryId);
            ViewData["ResellerId"] = new SelectList(_context.Reseller, "ResellerId", "TradingName", reseller_Service.ResellerId);
            return View(reseller_Service);
        }

        // POST: Reseller_Service/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResellerServiceId,ResellerId,ShortDescription,CategoryId,Task,Price,Metric")] Reseller_Service reseller_Service)
        {
            if (id != reseller_Service.ResellerServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reseller_Service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Reseller_ServiceExists(reseller_Service.ResellerServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", reseller_Service.CategoryId);
            ViewData["ResellerId"] = new SelectList(_context.Reseller, "ResellerId", "TradingName", reseller_Service.ResellerId);
            return View(reseller_Service);
        }

        // POST: Reseller_Service/Delete/5
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reseller_Service = await _context.Reseller_Service.SingleOrDefaultAsync(m => m.ResellerServiceId == id);
            _context.Reseller_Service.Remove(reseller_Service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Reseller_ServiceExists(int id)
        {
            return _context.Reseller_Service.Any(e => e.ResellerServiceId == id);
        }
    }
}

ServiceAssetTracker/Views/Reseller_Service/Create.cshtml
@model ServiceAssetTracker.Models.ResellerViewModels.Reseller_Service

@{
    ViewData["Title"] = "Add Reseller Service";
}


<div class="row">

    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Reseller Service</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>
                                Add Reseller Service
                            </h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />
                            <form asp-action="Create" data-parsley-validate class="form-horizontal form-label-left">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="ResellerId" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Reseller ID
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select asp-for="ResellerId" autofocus class="form-control col-md-7 col-xs-12" asp-items="ViewBag.ResellerId">
                                            <option selected>Select</option>
                                        </select>
                                        <span asp-validation-for="ResellerId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ShortDescription" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Short Description
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="ShortDescription" autofocus class="form-control col-md-7 col-xs-12" />
                                        <span asp-validation-for="ShortDescription" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="CategoryId" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Category ID
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
                                            <option selected>Select</option>
                                        </select>
                                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Task" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Task
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Task" class="form-control col-md-7 col-xs-12" />
                                        <span asp-validation-for="Task" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Price" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Price
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Price" class="form-control col-md-7 col-xs-12" />
                                        <span asp-validation-for="Price" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Metric" class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Metric
                                        <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Metric" class="form-control col-md-7 col-xs-12" />
                                        <span asp-validation-for="Metric" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <a asp-action="Index" class="btn btn-primary">Back To List</a>
                                        <button class="btn btn-primary" type="reset">Reset</button>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceAssetTracker/Views/Reseller_Service/Delete.cshtml
@model ServiceAssetTracker.Models.ResellerViewModels.Reseller_Service

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reseller_Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Task)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Task)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Metric)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Metric)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Categories.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reseller)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reseller.ResellerId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ResellerServiceId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ServiceAssetTracker/Views/Reseller_Service/Details.cshtml
@model ServiceAssetTracker.Models.ResellerViewModels.Reseller_Service

@{
    ViewData["Title"] = "Details";
}

<hr />

<div class="row">
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Reseller Service</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>
                                Detail Reseller Service
                            </h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />
                            <form data-parsley-validate class="form-horizontal form-label-left">
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="ResellerServiceId">
                                        Service ID
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="ResellerServiceId" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="ResellerId">
                                        Reseller ID
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Reseller.TradingName" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="ShortDescription">
                                        Short Description
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="ShortDescription" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="CategoryId">
                                        Category ID
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Categories.Name" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Task">
                                        Task
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Task" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Price">
                                        Price
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Price" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Metric">
                                        Metric
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input asp-for="Metric" readonly class="form-control col-md-7 col-xs-12" />
                                    </div>
                                </div>

                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                                        <a asp-action="Edit" asp-route-id="@Model.ResellerId" class="btn btn-success">Edit</a>
                                        <a data-toggle="modal" data-target="#deleteModal" class="btn btn-danger">Delete</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    @Html.Partial("_DeleteModal");
    var url = "/Reseller_Service/DeleteConfirmed/" + Model.ResellerServiceId;
}
<input type="hidden" id="hdnUrl" value="@url" />

ServiceAssetTracker/Views/Reseller_Service/Index.cshtml
@model IEnumerable<ServiceAssetTracker.Models.ResellerViewModels.Reseller_Service>

@{
    ViewData["Title"] = "List Reseller Services";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Reseller Service</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List Reseller Service</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a asp-action="" class="btn btn-success">Import CSV</a>
                            </li>
                            <li>
                                <a asp-action="Create" class="btn btn-primary">Add Reseller Service</a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">Service ID</th>
                                    <th class="column-title">Reseller ID </th>
                                    <th class="column-title">Short Description</th>
                                    <th class="column-title">Category ID</th>
                                    <th class="column-title">Task</th>
                                    <th class="column-title">Price</th>
                                    <th class="column-title no-link last">Metric</th>
                                </tr>
                            </thead>


                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a asp-controller="Reseller_Service" asp-action="Details" asp-route-id="@item.ResellerServiceId">
                                                @Html.DisplayFor(modelItem => item.ResellerServiceId)
                                            </a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Reseller.TradingName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ShortDescription)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Categories.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Task)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Price)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Metric)
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>